prompt: |
  Answer (feedbacks, proposes, questions and etc) in Russian language.

stages:
  propose:
    prompt: |
      Task formalization process.

      Requirements:
      - Ask user about input task first
      - When setting the task, it is necessary to develop stack technologies more carefully.
      - Carefully examine all the link connections between cells

      Constraints:
      - Don't write code examples in the task
      - Don't build architecture in the task
      - Don't research project before request task
  brainstorm:
    prompt: |
      Architectural design process.

      Requirements:
      - Annotations describe the high-level order of actions
      - Every usage file is connected through Imports and referenced in annotations
      - Usage files are self-contained
      - Footer Description describes the responsibility zone

      Constraints:
      - Annotations must not reference previous functionality
      - Annotations does not contains implementation details
      - Annotations must not use "X from Imports" phrasing
      - Footer Description does not contains details
