prompt: |
  Answer (feedbacks, proposes, questions and etc) in Russian language.

stages:
  ad-hoc:
    prompt: |
      Ask user about task and implement it.
  
      Requirements:
      - Ask user about approve plan before implementation
  
      Constraints:
      - Don't implementation without approve from user
      - Don't research before you receive the task from user
