docs_dir: docs

site_name: Swax
site_description: Swax is tool for test plan generation based on AI
site_url: https://qarium.github.io/swax/
repo_url: https://github.com/qarium/gswax
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  logo: https://avatars.githubusercontent.com/u/262344922?s=200&v=4
  palette:
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        media: "(prefers-color-scheme: light)"
    - scheme: slate
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        media: "(prefers-color-scheme: dark)"
  features:
    - navigation.tabs
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy

nav: []

plugins:
  - search
