name: Notify Release

on:
  workflow_run:
    workflows: ["Publish Release"]
    types: [completed]

permissions:
  contents: read

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: qarium/ci/.github/workflows/library-notify.yml@0.0.x
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
